// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMRx7nS-eTTwy0BzsM8cvBZmnpD6-WZ4',
    appId: '1:1027159646827:web:1f7eb820027ed41a69872e',
    messagingSenderId: '1027159646827',
    projectId: 'iconsent-92393',
    authDomain: 'iconsent-92393.firebaseapp.com',
    storageBucket: 'iconsent-92393.appspot.com',
    measurementId: 'G-P888REM9RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Nf7afbRtMmWhroAKkwiL-bZCgI_OLjg',
    appId: '1:1027159646827:android:e2301ee35bbd327069872e',
    messagingSenderId: '1027159646827',
    projectId: 'iconsent-92393',
    storageBucket: 'iconsent-92393.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_dR-cF5uNsnPTUUGnGtbJXiI2_iZnpI',
    appId: '1:1027159646827:ios:bbb89ec0f153fef369872e',
    messagingSenderId: '1027159646827',
    projectId: 'iconsent-92393',
    storageBucket: 'iconsent-92393.appspot.com',
    iosBundleId: 'com.iconsent.app',
  );

}